### ISSUE TITLE
Support for ME2

### ISSUE THREAD

**Issue by Ralf27** [Mgamerz/ME3-GUI-Transplanter#1]
It would be great if it would work with ME2 files too

**Comment by Mgamerz** [comment]
This feature has been implemented into my fork of ME3Explorer as it will be much easier to support this feature there. You can find this build here: https://github.com/Mgamerz/ME3Explorer/releases/tag/3.1.2.10

To use this feature, find a BioSWF or GFxMovieExport in Package Editor, and while in tree view, right click the export. You will see Scaleform SWF menu, from here you can choose to export or replace. If you have issues with this feature, please report them on my fork's issue page: https://github.com/Mgamerz/ME3Explorer/issues.

Thanks,
Mgamerz
